version: "3"
services:
  
  bdd:
    image: paragpatil7/selenium-docker-bdd
    shm_size: '1gb'
    depends_on: 
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - CUCUMBER_OPTIONS=classpath:features
    volumes:
      - ./output:/usr/share/Parag/target/cucumber-reports